import { IconX } from '@tabler/icons-react'

function AuthAuditSection({ events, stats, onOpenUsers }) {
  return <section className="admin-audit"><div className="section-heading"><div><span className="eyebrow">Kontosicherheit</span><h2>Registrierungen & Anmeldungen</h2></div><span>{events.length}</span></div><p>Erfolgreiche Registrierungen und Anmeldungen der letzten 100 Ereignisse.</p><div className="admin-kpis" aria-label="BoulderO Kennzahlen"><button type="button" className="admin-kpi-button" onClick={onOpenUsers} aria-label="Registrierte Nutzer anzeigen"><strong>{stats?.registered_users ?? '–'}</strong><span>Registrierte Nutzer</span></button><div><strong>{stats?.journal_entries ?? '–'}</strong><span>Beiträge</span></div><div><strong>{stats?.active_spots ?? '–'}</strong><span>Aktive Hallen</span></div></div><div className="admin-table-wrap"><table><thead><tr><th>Zeitpunkt</th><th>Ereignis</th><th>Konto</th><th>E-Mail</th></tr></thead><tbody>{events.length ? events.map((event) => <tr key={event.id}><td>{new Intl.DateTimeFormat('de-DE', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(event.created_at))}</td><td><span className={`audit-event audit-event--${event.event_type}`}>{event.event_type === 'registration' ? 'Registrierung' : 'Anmeldung'}</span></td><td>{event.user_name}</td><td>{event.user_email}</td></tr>) : <tr><td colSpan="4">Noch keine Ereignisse seit der Aktivierung des Audits.</td></tr>}</tbody></table></div></section>
}

export function RegisteredUsersDialog({ users, total, loading, onClose }) {
  return <div className="composer-backdrop"><section className="journal-composer admin-users-dialog" role="dialog" aria-modal="true" aria-label="Registrierte Nutzer"><div className="composer-header"><div><span className="eyebrow">Kontosicherheit</span><h2>Registrierte Nutzer</h2></div><button type="button" className="icon-button ui-icon-button" onClick={onClose} aria-label="Schließen"><IconX size={19} /></button></div><p className="auth-copy">{total > users.length ? `Die ersten ${users.length} von ${total} angelegten BoulderO-Konten.` : 'Alle angelegten BoulderO-Konten.'}</p><div className="admin-table-wrap"><table><thead><tr><th>Nutzer</th><th>E-Mail</th><th>Registriert</th><th>Letzte Anmeldung</th></tr></thead><tbody>{loading ? <tr><td colSpan="4">Nutzer werden geladen …</td></tr> : users.length ? users.map((user) => <tr key={user.id}><td><span className="admin-user"><span className="person-avatar">{user.image ? <img src={`/api/avatars/${user.id}`} alt="" /> : user.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><span><b>{user.name}</b><small>@{user.username}</small></span></span></td><td>{user.email}</td><td>{new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium' }).format(new Date(user.created_at))}</td><td>{user.last_login_at ? new Intl.DateTimeFormat('de-DE', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(user.last_login_at)) : 'Noch keine'}</td></tr>) : <tr><td colSpan="4">Keine registrierten Nutzer gefunden.</td></tr>}</tbody></table></div></section></div>
}

export function AuditView({ events, stats, onBack, onOpenUsers }) {
  return <main className="view content-view compact-view admin-view"><div className="admin-page-content"><div className="page-intro"><span className="eyebrow">BoulderO Verwaltung</span><h1>Kontosicherheit</h1><p>Überblick über erfolgreiche Registrierungen und Anmeldungen.</p></div><AuthAuditSection events={events} stats={stats} onOpenUsers={onOpenUsers} /><button className="text-back" onClick={onBack}>Zurück zum Profil</button></div></main>
}
